#!/usr/bin/env python3
"""Compile the root certificates under certs/ into the ESP-IDF bundle format.

Every ``certs/*.pem`` (one root CA each; lines outside the BEGIN/END block
are comments - provenance, SHA-256 fingerprint) becomes one entry of the
bundle that ``WiFiClientSecure::setCACertBundle()`` (Arduino-ESP32 2.0.17,
``esp_crt_bundle.c``) verifies server chains against. The format is the one
of the IDF's ``gen_crt_bundle.py``: a big-endian count, then per root a
4-byte header (subject length, public-key length), the DER ``Name`` of the
subject and the DER ``SubjectPublicKeyInfo`` - ~0.2-0.6 KB per root instead
of 0.8-1.9 KB of PEM. Entries are sorted by the subject bytes because the
verifier binary-searches them by the child's issuer.

The header is written to ``src/generated/ca_bundle.h`` (git-ignored, a build
product like the web assets) only when its content changed:

    python scripts/build_ca_bundle.py            # standalone
    python scripts/build_ca_bundle.py --check    # print sizes only

Registered in platformio.ini as a PlatformIO pre-script. No third-party
Python module is needed: the few DER fields are read with a 30-line walker.
"""

import base64
import hashlib
import os
import re
import struct
import sys

_PEM_RE = re.compile(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", re.S)


def _tlv(der, off):
    """Return (tag, header_len, content_len) of the DER element at ``off``."""
    tag = der[off]
    ln = der[off + 1]
    if ln < 0x80:
        return tag, 2, ln
    n = ln & 0x7F
    return tag, 2 + n, int.from_bytes(der[off + 2:off + 2 + n], "big")


def _children(der, off, end):
    """Yield (tag, start, end_of_element) for every element between off and end."""
    while off < end:
        tag, hl, cl = _tlv(der, off)
        yield tag, off, off + hl + cl
        off += hl + cl


def subject_and_spki(der):
    """DER ``Name`` (subject) and ``SubjectPublicKeyInfo`` of an X.509 certificate."""
    tag, hl, cl = _tlv(der, 0)
    if tag != 0x30:
        raise RuntimeError("build_ca_bundle: not a DER certificate")
    tbs_tag, tbs_off, _tbs_end = next(_children(der, hl, hl + cl))
    if tbs_tag != 0x30:
        raise RuntimeError("build_ca_bundle: no tbsCertificate")
    _t, thl, tcl = _tlv(der, tbs_off)
    fields = list(_children(der, tbs_off + thl, tbs_off + thl + tcl))
    if fields and fields[0][0] == 0xA0:      # explicit version
        fields = fields[1:]
    # serial, signature, issuer, validity, subject, subjectPublicKeyInfo
    _serial, _sig, _issuer, _validity, subject, spki = fields[:6]
    return der[subject[1]:subject[2]], der[spki[1]:spki[2]]


def _cn(subject_der):
    """Best-effort commonName (2.5.4.3) of a DER Name, for the header comment."""
    i = subject_der.find(b"\x06\x03\x55\x04\x03")
    if i < 0:
        return "?"
    tag, hl, cl = _tlv(subject_der, i + 5)
    return subject_der[i + 5 + hl:i + 5 + hl + cl].decode("utf-8", "replace")


def build(project_dir, write=True, verbose=True):
    cert_dir = os.path.join(project_dir, "certs")
    out_path = os.path.join(project_dir, "src", "generated", "ca_bundle.h")
    names = sorted(n for n in os.listdir(cert_dir) if n.endswith(".pem"))
    if not names:
        raise RuntimeError("build_ca_bundle: no .pem files in %s" % cert_dir)

    roots = []
    for name in names:
        with open(os.path.join(cert_dir, name), "r", encoding="utf-8") as f:
            m = _PEM_RE.search(f.read())
        if not m:
            raise RuntimeError("build_ca_bundle: %s has no PEM certificate" % name)
        der = base64.b64decode("".join(m.group(1).split()))
        subject, spki = subject_and_spki(der)
        fp = hashlib.sha256(der).hexdigest().upper()
        roots.append((subject, spki, name, fp, len(der)))
        if verbose:
            print("[build_ca_bundle] %-30s subject %3d B + key %3d B = %4d B (DER %4d B) %s"
                  % (name, len(subject), len(spki), 4 + len(subject) + len(spki), len(der), _cn(subject)))

    roots.sort(key=lambda r: r[0])           # the verifier binary-searches by subject bytes
    bundle = struct.pack(">H", len(roots))
    for subject, spki, _name, _fp, _n in roots:
        bundle += struct.pack(">HH", len(subject), len(spki)) + subject + spki
    if verbose:
        print("[build_ca_bundle] %d roots -> %d B bundle" % (len(roots), len(bundle)))

    lines = [
        "// Generated by scripts/build_ca_bundle.py from certs/*.pem - DO NOT EDIT.",
        "// ESP-IDF certificate-bundle format (subject + public key per root, sorted",
        "// by subject) for WiFiClientSecure::setCACertBundle(). Roots:",
    ]
    for subject, _spki, name, fp, _n in roots:
        lines.append("//   %-40s %s  SHA-256 %s" % (_cn(subject), name, fp))
    lines += [
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <pgmspace.h>",
        "",
        "static const uint8_t TICKR_CA_BUNDLE[] PROGMEM = {",
    ]
    for i in range(0, len(bundle), 24):
        lines.append("  " + ",".join("0x%02x" % b for b in bundle[i:i + 24]) + ",")
    lines += [
        "};",
        "static const size_t TICKR_CA_BUNDLE_LEN = %d;" % len(bundle),
        "static const uint8_t TICKR_CA_BUNDLE_ROOTS = %d;" % len(roots),
        "",
    ]
    content = "\n".join(lines)

    if write:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        old = None
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as f:
                old = f.read()
        if old != content:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(content)
            if verbose:
                print("[build_ca_bundle] wrote %s" % os.path.relpath(out_path, project_dir))
        elif verbose:
            print("[build_ca_bundle] %s is up to date" % os.path.relpath(out_path, project_dir))
    return len(bundle)


def _cli(argv):
    project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    try:
        build(project_dir, write="--check" not in argv)
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        return 1
    return 0


try:
    Import("env")  # noqa: F821 - only defined when run by SCons/PlatformIO
except NameError:
    sys.exit(_cli(sys.argv[1:]))
else:
    build(env.subst("$PROJECT_DIR"))  # noqa: F821
