#!/usr/bin/env python3
"""Compile the web UI (www/src/) into gzip-compressed PROGMEM arrays.

Every ``www/src/<name>.<ext>`` that does not start with ``_`` becomes one asset:
``{{include:<file>}}`` directives are expanded (recursively, relative to
``www/src/``), leading indentation and blank lines are stripped, the result is
gzip'ed (level 9, deterministic - no mtime, no file name) and written to
``src/web/generated/www_assets.h`` as

    static const uint8_t WWW_<NAME>_GZ[] PROGMEM = {...};
    static const WwwAsset WWW_ASSETS[] = {{"<name>.<ext>", "<mime>", data, len, "<etag>"}, ...};

Files starting with ``_`` are partials (only usable through ``{{include:}}``).
The header is rewritten only when its content changed, so incremental builds
stay incremental. The generated file is git-ignored: it is a build product,
regenerated by every ``pio run`` (PlatformIO pre-script) and by

    python scripts/build_www.py            # standalone, e.g. before `pio check`
    python scripts/build_www.py --check    # only print sizes / enforce the gate

Size gate: the sum of all gzipped assets must stay below WWW_GZ_LIMIT bytes
(docs/DEVELOPMENT.md "Web UI") - the build fails otherwise, so UI growth is a
conscious decision rather than an accident.

Developer-only pages (DEV_ONLY, today ``dev.html`` = ``/dev``) are emitted
inside ``#ifdef TICKR_DEV_PAGE`` so one generated header serves both the
release image (``tickr``, without them) and ``tickr_dev`` (with them, the flag
is set in platformio.ini). The gate applies to the release total; the dev
total is printed for information.
"""

import gzip
import os
import re
import sys
import zlib

WWW_GZ_LIMIT = 40 * 1024   # gzipped release assets (docs/DEVELOPMENT.md "Web UI")
DEV_ONLY = {"dev.html"}    # served only by tickr_dev (-DTICKR_DEV_PAGE)
DEV_DEFINE = "TICKR_DEV_PAGE"

MIME = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".txt": "text/plain",
}

_INCLUDE_RE = re.compile(r"\{\{include:([A-Za-z0-9_.\-/]+)\}\}")


def _read(src_dir, name, stack):
    if name in stack:
        raise RuntimeError("build_www: include loop: %s" % " -> ".join(stack + [name]))
    path = os.path.join(src_dir, name)
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    def _sub(m):
        return _read(src_dir, m.group(1), stack + [name])

    return _INCLUDE_RE.sub(_sub, text)


def _strip(text):
    """Drop leading indentation, blank lines and whole-line comments (a line
    that is only a ``//`` JS comment or a one-line ``/* */`` CSS/JS comment).
    Newlines are kept, so HTML whitespace semantics do not change (a newline is
    still whitespace). Sources therefore must not start a line inside a string
    literal with ``//`` or ``/*``."""
    out = []
    for line in text.split("\n"):
        line = line.lstrip().rstrip()
        if not line:
            continue
        if line.startswith("//") or (line.startswith("/*") and line.endswith("*/")):
            continue
        out.append(line)
    return "\n".join(out) + "\n"


def _c_ident(name):
    return "WWW_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper() + "_GZ"


try:
    import zopfli.gzip as _zopfli   # optional: `pip install zopfli`, 2-3 % smaller gzip streams
except ImportError:                 # pragma: no cover - depends on the host
    _zopfli = None

# Which compressor produced the header (printed once; the two differ in size,
# so a reproducible build needs the same choice on every machine - CI installs
# zopfli, see docs/DEVELOPMENT.md "Web UI").
COMPRESSOR = "zopfli" if _zopfli else "zlib"


def _gzip(data):
    # Both paths are deterministic for identical input: no mtime, no file name.
    # Zopfli emits the same gzip container (plain deflate inside), so the
    # device and the browsers see no difference.
    if _zopfli:
        return _zopfli.compress(data, numiterations=50)
    return gzip.compress(data, compresslevel=9, mtime=0)


def build(project_dir, write=True, verbose=True):
    src_dir = os.path.join(project_dir, "www", "src")
    out_path = os.path.join(project_dir, "src", "web", "generated", "www_assets.h")

    names = sorted(
        n for n in os.listdir(src_dir)
        if not n.startswith("_") and not n.startswith(".") and os.path.splitext(n)[1] in MIME
    )
    if not names:
        raise RuntimeError("build_www: no assets found in %s" % src_dir)

    assets = []
    total_raw = total_gz = dev_gz = 0
    for name in names:
        text = _strip(_read(src_dir, name, []))
        raw = text.encode("utf-8")
        gz = _gzip(raw)
        etag = "%08x" % (zlib.crc32(gz) & 0xFFFFFFFF)
        dev = name in DEV_ONLY
        assets.append((name, MIME[os.path.splitext(name)[1]], raw, gz, etag, dev))
        if dev:
            dev_gz += len(gz)
        else:
            total_raw += len(raw)
            total_gz += len(gz)
        if verbose:
            print("[build_www] %-14s %6d B raw -> %5d B gz  etag %s%s"
                  % (name, len(raw), len(gz), etag, "  (tickr_dev only)" if dev else ""))
    if verbose:
        print("[build_www] release total %d B raw -> %d B gz (gate %d B, %.0f%% used, %s); tickr_dev total %d B gz"
              % (total_raw, total_gz, WWW_GZ_LIMIT, total_gz * 100.0 / WWW_GZ_LIMIT, COMPRESSOR, total_gz + dev_gz))
    if total_gz > WWW_GZ_LIMIT:
        raise RuntimeError("build_www: gzipped web assets are %d B, over the %d B gate (see docs/DEVELOPMENT.md)"
                           % (total_gz, WWW_GZ_LIMIT))

    lines = [
        "// Generated by scripts/build_www.py from www/src/ - DO NOT EDIT, edit the sources.",
        "// Every asset is gzip'ed; serve with Content-Encoding: gzip (see src/web/www.cpp).",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <pgmspace.h>",
        '#include "../www.h"',
        "",
    ]
    for name, _mime, _raw, gz, _etag, dev in assets:
        ident = _c_ident(name)
        if dev:
            lines.append("#ifdef %s" % DEV_DEFINE)
        lines.append("// %s: %d bytes" % (name, len(gz)))
        lines.append("static const uint8_t %s[] PROGMEM = {" % ident)
        for i in range(0, len(gz), 24):
            lines.append("  " + ",".join("0x%02x" % b for b in gz[i:i + 24]) + ",")
        lines.append("};")
        if dev:
            lines.append("#endif")
        lines.append("")
    lines.append("static const WwwAsset WWW_ASSETS[] = {")
    for name, mime, _raw, gz, etag, dev in assets:
        if dev:
            lines.append("#ifdef %s" % DEV_DEFINE)
        lines.append('  {"%s", "%s", %s, %d, "\\"%s\\""},' % (name, mime, _c_ident(name), len(gz), etag))
        if dev:
            lines.append("#endif")
    lines.append("};")
    lines.append("static const size_t WWW_ASSETS_COUNT = sizeof(WWW_ASSETS) / sizeof(WWW_ASSETS[0]);")
    lines.append("#ifdef %s" % DEV_DEFINE)
    lines.append("static const size_t WWW_ASSETS_GZ_TOTAL = %d;" % (total_gz + dev_gz))
    lines.append("#else")
    lines.append("static const size_t WWW_ASSETS_GZ_TOTAL = %d;" % total_gz)
    lines.append("#endif")
    lines.append("")
    content = "\n".join(lines)

    if write:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        old = None
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as f:
                old = f.read()
        if old != content:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(content)
            if verbose:
                print("[build_www] wrote %s" % os.path.relpath(out_path, project_dir))
        elif verbose:
            print("[build_www] %s is up to date" % os.path.relpath(out_path, project_dir))
    return total_gz


def _cli(argv):
    project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    check_only = "--check" in argv
    try:
        build(project_dir, write=not check_only)
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        return 1
    return 0


try:
    Import("env")  # noqa: F821 - only defined when run by SCons/PlatformIO
except NameError:
    sys.exit(_cli(sys.argv[1:]))
else:
    # Pre-script: the header must exist before the first .cpp is compiled.
    build(env.subst("$PROJECT_DIR"))  # noqa: F821
